# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09fe359252cd5da94ec4d5c1a12798cc28852e882740174e4799b3b0ab0fa9c8ac0e2ace9e3a39979e4efa5632fd57e19620a500f6612b3d86d58868b082d41b

test:
  secret_key_base: 31dc1e414827387f48f2d66bd791b37748e48e4eb50614acf4bd1db98fdd0296eb554220bf979df3347f2fec700aaaaf6d70031c0cad77aecc87f2150e5cb9a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
